image: docker:19.03.13

services:
  - docker:19.03.13-dind

stages:
  - build

build:
  stage: build
  before_script:
    - echo $CI_REGISTRY_PASSWORD | docker login --username $CI_REGISTRY_USER --password-stdin
  script:
    - export VERSION=$(cat package.json | grep version | head -1 | sed 's/[version,",:]//g' | tr -d [:space:])
    - docker build --no-cache
      --tag $CI_REGISTRY_IMAGE:$VERSION
      --tag $CI_REGISTRY_IMAGE:latest
      --build-arg NODE_ENV=$NODE_ENV
      --build-arg SERVER_URL=$SERVER_URL
      --build-arg SERVER_URL_PATH=$SERVER_URL_PATH
      --build-arg LOCAL_STORAGE_KEY=$LOCAL_STORAGE_KEY
      --build-arg SERVER_UPLOAD_IMAGE_URL=$SERVER_UPLOAD_IMAGE_URL
      --build-arg SERVER_URL_IMAGE=$SERVER_URL_IMAGE
      --build-arg SERVER_UPLOAD_IMAGE_URL_PROFILE_PATH=$SERVER_UPLOAD_IMAGE_URL_PROFILE_PATH
      --build-arg SERVER_UPLOAD_IMAGE_URL_ARTICLE_PATH=$SERVER_UPLOAD_IMAGE_URL_ARTICLE_PATH .
    - docker push $CI_REGISTRY_IMAGE:$VERSION
    - docker push $CI_REGISTRY_IMAGE:latest
