image: node:12.18

stages:
  - build-to-gcp-registry
  - deploy-to-gke-cluster
  - build-to-docker-hub

build-to-docker-hub:
  services:
    - name: docker:19.03.13-dind
  image: docker:19.03.13
  stage: build-to-docker-hub
  before_script:
    - echo $CI_REGISTRY_PASSWORD | docker login --username $CI_REGISTRY_USER --password-stdin
  script:
    - export VERSION=$(cat package.json | grep version | head -1 | sed 's/[version,",:]//g' | tr -d [:space:])
    - docker build --no-cache
      --tag $CI_REGISTRY_IMAGE:$VERSION
      --tag $CI_REGISTRY_IMAGE:latest
      --build-arg NODE_ENV=$NODE_ENV
      --build-arg SERVER_URL=$SERVER_URL
      --build-arg SERVER_URL_PATH=$SERVER_URL_PATH
      --build-arg LOCAL_STORAGE_KEY=$LOCAL_STORAGE_KEY
      --build-arg SERVER_UPLOAD_IMAGE_URL=$SERVER_UPLOAD_IMAGE_URL
      --build-arg SERVER_URL_IMAGE=$SERVER_URL_IMAGE
      --build-arg SERVER_UPLOAD_IMAGE_URL_PROFILE_PATH=$SERVER_UPLOAD_IMAGE_URL_PROFILE_PATH
      --build-arg SERVER_UPLOAD_IMAGE_URL_ARTICLE_PATH=$SERVER_UPLOAD_IMAGE_URL_ARTICLE_PATH .
    - docker push $CI_REGISTRY_IMAGE:$VERSION
    - docker push $CI_REGISTRY_IMAGE:latest

build-to-gcp-registry:
  services:
    - name: docker:19.03.13-dind
  image: docker:19.03.13
  stage: build-to-gcp-registry
  before_script:
    - base64 -d $GCP_SA_KEY | docker login -u _json_key --password-stdin https://asia.gcr.io
  script:
    - export VERSION=$(cat package.json | grep version | head -1 | sed 's/[version,",:]//g' | tr -d [:space:])
    - docker build --no-cache
      --tag asia.gcr.io/$PROJECT_ID/$IMAGE_NAME:$VERSION
      --tag asia.gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
      --build-arg NODE_ENV=$NODE_ENV
      --build-arg SERVER_URL=$SERVER_URL
      --build-arg SERVER_URL_PATH=$SERVER_URL_PATH
      --build-arg LOCAL_STORAGE_KEY=$LOCAL_STORAGE_KEY
      --build-arg SERVER_UPLOAD_IMAGE_URL=$SERVER_UPLOAD_IMAGE_URL
      --build-arg SERVER_URL_IMAGE=$SERVER_URL_IMAGE
      --build-arg SERVER_UPLOAD_IMAGE_URL_PROFILE_PATH=$SERVER_UPLOAD_IMAGE_URL_PROFILE_PATH
      --build-arg SERVER_UPLOAD_IMAGE_URL_ARTICLE_PATH=$SERVER_UPLOAD_IMAGE_URL_ARTICLE_PATH .
    - docker push asia.gcr.io/$PROJECT_ID/$IMAGE_NAME:$VERSION
    - docker push asia.gcr.io/$PROJECT_ID/$IMAGE_NAME:latest

deploy-to-gke-cluster:
  services:
    - name: docker:19.03.13-dind
  image: google/cloud-sdk
  stage: deploy-to-gke-cluster
  before_script:
    - base64 -d $GCP_SA_KEY > ${HOME}/gcloud-service-key.json
    - gcloud auth activate-service-account --key-file ${HOME}/gcloud-service-key.json
    - gcloud container clusters get-credentials memorize-cluster --zone australia-southeast1-a --project $PROJECT_ID
    - export VERSION=$(cat package.json | grep version | head -1 | sed 's/[version,",:]//g' | tr -d [:space:])
  script:
    - kubectl set image deployment/memorize-frontend memorize-frontend=asia.gcr.io/$PROJECT_ID/$IMAGE_NAME:$VERSION --record
