image: node:12.18

stages:
  - build-to-gcp-registry
  - deploy-to-gke-cluster
  - build-to-docker-hub

build-to-docker-hub:
  services:
    - name: docker:19.03.13-dind
  image: docker:19.03.13
  only:
    refs:
      - main
  stage: build-to-docker-hub
  before_script:
    - echo $DOCKER_HUB_REGISTRY_PASSWORD | docker login --username $DOCKER_HUB_REGISTRY_USER --password-stdin
    - export VERSION=$(cat package.json | grep version | head -1 | sed 's/[version,",:]//g' | tr -d [:space:])
    - export REGISTRY_IMAGE=$($DOCKER_HUB_REGISTRY_USER/$IMAGE_NAME)
  script:
    - docker build --no-cache
      --tag $REGISTRY_IMAGE:$VERSION
      --tag $REGISTRY_IMAGE:latest
      --build-arg NODE_ENV=$NODE_ENV
      --build-arg SERVER_URL=$SERVER_URL
      --build-arg SERVER_URL_PATH=$SERVER_URL_PATH
      --build-arg LOCAL_STORAGE_KEY=$LOCAL_STORAGE_KEY
      --build-arg SERVER_UPLOAD_IMAGE_PATH=$SERVER_UPLOAD_IMAGE_PATH
      --build-arg SERVER_UPLOAD_IMAGE_PATH_PROFILE=$SERVER_UPLOAD_IMAGE_PATH_PROFILE
      --build-arg SERVER_UPLOAD_IMAGE_PATH_ARTICLE=$SERVER_UPLOAD_IMAGE_PATH_ARTICLE .
    - docker push $REGISTRY_IMAGE:$VERSION
    - docker push $REGISTRY_IMAGE:latest

build-to-gcp-registry:
  services:
    - name: docker:19.03.13-dind
  image: docker:19.03.13
  only:
    refs:
      - main
  stage: build-to-gcp-registry
  before_script:
    - base64 -d $GCP_SA_KEY | docker login -u _json_key --password-stdin https://asia.gcr.io
    - export VERSION=$(cat package.json | grep version | head -1 | sed 's/[version,",:]//g' | tr -d [:space:])
  script:
    - docker build --no-cache
      --tag asia.gcr.io/$PROJECT_ID/$IMAGE_NAME:$VERSION
      --tag asia.gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
      --build-arg NODE_ENV=$NODE_ENV
      --build-arg SERVER_URL=$SERVER_URL
      --build-arg SERVER_URL_PATH=$SERVER_URL_PATH
      --build-arg LOCAL_STORAGE_KEY=$LOCAL_STORAGE_KEY
      --build-arg SERVER_UPLOAD_IMAGE_PATH=$SERVER_UPLOAD_IMAGE_PATH
      --build-arg SERVER_UPLOAD_IMAGE_PATH_PROFILE=$SERVER_UPLOAD_IMAGE_PATH_PROFILE
      --build-arg SERVER_UPLOAD_IMAGE_PATH_ARTICLE=$SERVER_UPLOAD_IMAGE_PATH_ARTICLE .
    - docker push asia.gcr.io/$PROJECT_ID/$IMAGE_NAME:$VERSION
    - docker push asia.gcr.io/$PROJECT_ID/$IMAGE_NAME:latest

deploy-to-gke-cluster:
  services:
    - name: docker:19.03.13-dind
  image: google/cloud-sdk
  only:
    refs:
      - main
  stage: deploy-to-gke-cluster
  before_script:
    - base64 -d $GCP_SA_KEY > ${HOME}/gcloud-service-key.json
    - gcloud auth activate-service-account --key-file ${HOME}/gcloud-service-key.json
    - gcloud container clusters get-credentials $GCP_CLUSTER_NAME --zone $GCP_CLUSTER_ZONE --project $PROJECT_ID
    - export VERSION=$(cat package.json | grep version | head -1 | sed 's/[version,",:]//g' | tr -d [:space:])
  script:
    - kubectl set image deployment/$DEPLOYMENT_NAME $DEPLOYMENT_NAME=asia.gcr.io/$GCP_PROJECT_ID/$IMAGE_NAME:$VERSION --record
