FROM node:lts

ARG NODE_ENV=production
ENV NODE_ENV=$NODE_ENV
RUN echo $NODE_ENV

ENV LOCAL_STORAGE_KEY=current_user

ARG SERVER_URL
ENV SERVER_URL=$SERVER_URL
RUN echo $SERVER_URL

ARG SERVER_URL_PATH
ENV SERVER_URL_PATH=$SERVER_URL_PATH
RUN echo $SERVER_URL_PATH

ARG SERVER_UPLOAD_IMAGE_PATH
ENV SERVER_UPLOAD_IMAGE_PATH=$SERVER_UPLOAD_IMAGE_PATH
RUN echo $SERVER_UPLOAD_IMAGE_PATH

ARG SERVER_UPLOAD_IMAGE_PATH_PROFILE
ENV SERVER_UPLOAD_IMAGE_PATH_PROFILE=$SERVER_UPLOAD_IMAGE_PATH_PROFILE
RUN echo $SERVER_UPLOAD_IMAGE_PATH_PROFILE

ARG SERVER_UPLOAD_IMAGE_PATH_ARTICLE
ENV SERVER_UPLOAD_IMAGE_PATH_ARTICLE=$SERVER_UPLOAD_IMAGE_PATH_ARTICLE
RUN echo $SERVER_UPLOAD_IMAGE_PATH_ARTICLE

# set a directory for the app
WORKDIR /usr/src/memorize-frontend

# copy all the files to the container
COPY package.json /usr/src/memorize-frontend

RUN npm install

COPY . /usr/src/memorize-frontend

RUN npm run build

# tell the port number the container should expose
EXPOSE 3000

# run the command
CMD ["npm", "run", "start"]
