export const STATUS_IDLE = 'STATUS_IDLE'
export const STATUS_SUCCESS = 'STATUS_SUCCESS'
export const STATUS_LOADING = 'STATUS_LOADING'
export const STATUS_ERROR = 'STATUS_ERROR'

export const SOCKET_CONNECTED = 'SOCKET_CONNECTED'
export const SOCKET_DISCONNECTED = 'SOCKET_DISCONNECTED'
export const SOCKET_ON_ARTICLE_CREATED = 'SOCKET_ON_ARTICLE_CREATED'
